import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface PermissionSeedData {
  code: string;
  screen: string;
  subScreen?: string;
  action: string;
  nameAr: string;
  nameEn: string;
  description?: string;
  category: string;
  isViewPermission: boolean;
}

/**
 * Permission Seed Data - 106 Permissions
 * Organized by 7 main screens
 */
const permissionsSeedData: PermissionSeedData[] = [
  // ============================================
  // 1. Customers (4 permissions)
  // ============================================
  {
    code: 'customers.view',
    screen: 'customers',
    action: 'view',
    nameAr: 'عرض العملاء',
    nameEn: 'View Customers',
    description: 'View customers screen and list',
    category: 'customers',
    isViewPermission: true,
  },
  {
    code: 'customers.create',
    screen: 'customers',
    action: 'create',
    nameAr: 'إضافة عميل',
    nameEn: 'Create Customer',
    description: 'Add new customer',
    category: 'customers',
    isViewPermission: false,
  },
  {
    code: 'customers.edit',
    screen: 'customers',
    action: 'edit',
    nameAr: 'تعديل عميل',
    nameEn: 'Edit Customer',
    description: 'Edit existing customer',
    category: 'customers',
    isViewPermission: false,
  },
  {
    code: 'customers.activate_deactivate',
    screen: 'customers',
    action: 'activate_deactivate',
    nameAr: 'تفعيل/تعطيل عميل',
    nameEn: 'Activate/Deactivate Customer',
    description: 'Change customer active status',
    category: 'customers',
    isViewPermission: false,
  },
  {
    code: 'customers.delete',
    screen: 'customers',
    action: 'delete',
    nameAr: 'حذف عميل',
    nameEn: 'Delete Customer',
    description: 'Delete a customer',
    category: 'customers',
    isViewPermission: false,
  },

  // ============================================
  // 2. Invoices (24 permissions - 6 per type × 4 types)
  // ============================================
  // Type 1: Export Invoices
  {
    code: 'invoices.type1.view',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'view',
    nameAr: 'عرض فواتير التصدير',
    nameEn: 'View Export Invoices',
    description: 'View export invoices screen',
    category: 'invoices',
    isViewPermission: true,
  },
  {
    code: 'invoices.type1.create',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'create',
    nameAr: 'إنشاء فاتورة تصدير',
    nameEn: 'Create Export Invoice',
    description: 'Create new export invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type1.preview',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'preview',
    nameAr: 'معاينة فاتورة تصدير',
    nameEn: 'Preview Export Invoice',
    description: 'Preview export invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type1.print',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'print',
    nameAr: 'طباعة فاتورة تصدير',
    nameEn: 'Print Export Invoice',
    description: 'Print export invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type1.edit',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'edit',
    nameAr: 'تعديل فاتورة تصدير',
    nameEn: 'Edit Export Invoice',
    description: 'Edit export invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type1.delete',
    screen: 'invoices',
    subScreen: 'type1',
    action: 'delete',
    nameAr: 'حذف فاتورة تصدير',
    nameEn: 'Delete Export Invoice',
    description: 'Delete export invoice',
    category: 'invoices',
    isViewPermission: false,
  },

  // Type 2: Import Invoices
  {
    code: 'invoices.type2.view',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'view',
    nameAr: 'عرض فواتير الاستيراد',
    nameEn: 'View Import Invoices',
    description: 'View import invoices screen',
    category: 'invoices',
    isViewPermission: true,
  },
  {
    code: 'invoices.type2.create',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'create',
    nameAr: 'إنشاء فاتورة استيراد',
    nameEn: 'Create Import Invoice',
    description: 'Create new import invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type2.preview',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'preview',
    nameAr: 'معاينة فاتورة استيراد',
    nameEn: 'Preview Import Invoice',
    description: 'Preview import invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type2.print',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'print',
    nameAr: 'طباعة فاتورة استيراد',
    nameEn: 'Print Import Invoice',
    description: 'Print import invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type2.edit',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'edit',
    nameAr: 'تعديل فاتورة استيراد',
    nameEn: 'Edit Import Invoice',
    description: 'Edit import invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type2.delete',
    screen: 'invoices',
    subScreen: 'type2',
    action: 'delete',
    nameAr: 'حذف فاتورة استيراد',
    nameEn: 'Delete Import Invoice',
    description: 'Delete import invoice',
    category: 'invoices',
    isViewPermission: false,
  },

  // Type 3: Transit Invoices
  {
    code: 'invoices.type3.view',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'view',
    nameAr: 'عرض فواتير الترانزيت',
    nameEn: 'View Transit Invoices',
    description: 'View transit invoices screen',
    category: 'invoices',
    isViewPermission: true,
  },
  {
    code: 'invoices.type3.create',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'create',
    nameAr: 'إنشاء فاتورة ترانزيت',
    nameEn: 'Create Transit Invoice',
    description: 'Create new transit invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type3.preview',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'preview',
    nameAr: 'معاينة فاتورة ترانزيت',
    nameEn: 'Preview Transit Invoice',
    description: 'Preview transit invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type3.print',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'print',
    nameAr: 'طباعة فاتورة ترانزيت',
    nameEn: 'Print Transit Invoice',
    description: 'Print transit invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type3.edit',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'edit',
    nameAr: 'تعديل فاتورة ترانزيت',
    nameEn: 'Edit Transit Invoice',
    description: 'Edit transit invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type3.delete',
    screen: 'invoices',
    subScreen: 'type3',
    action: 'delete',
    nameAr: 'حذف فاتورة ترانزيت',
    nameEn: 'Delete Transit Invoice',
    description: 'Delete transit invoice',
    category: 'invoices',
    isViewPermission: false,
  },

  // Type 4: Free Invoices
  {
    code: 'invoices.type4.view',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'view',
    nameAr: 'عرض الفواتير الحرة',
    nameEn: 'View Free Invoices',
    description: 'View free invoices screen',
    category: 'invoices',
    isViewPermission: true,
  },
  {
    code: 'invoices.type4.create',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'create',
    nameAr: 'إنشاء فاتورة حرة',
    nameEn: 'Create Free Invoice',
    description: 'Create new free invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type4.preview',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'preview',
    nameAr: 'معاينة فاتورة حرة',
    nameEn: 'Preview Free Invoice',
    description: 'Preview free invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type4.print',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'print',
    nameAr: 'طباعة فاتورة حرة',
    nameEn: 'Print Free Invoice',
    description: 'Print free invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type4.edit',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'edit',
    nameAr: 'تعديل فاتورة حرة',
    nameEn: 'Edit Free Invoice',
    description: 'Edit free invoice',
    category: 'invoices',
    isViewPermission: false,
  },
  {
    code: 'invoices.type4.delete',
    screen: 'invoices',
    subScreen: 'type4',
    action: 'delete',
    nameAr: 'حذف فاتورة حرة',
    nameEn: 'Delete Free Invoice',
    description: 'Delete free invoice',
    category: 'invoices',
    isViewPermission: false,
  },

  // ============================================
  // 3. Shipping Agents (12 permissions - 4 per sub-screen × 3)
  // ============================================
  // Agents Management
  {
    code: 'shipping_agents.agents.view',
    screen: 'shipping_agents',
    subScreen: 'agents',
    action: 'view',
    nameAr: 'عرض الوكلاء',
    nameEn: 'View Agents',
    description: 'View agents management tab',
    category: 'shipping_agents',
    isViewPermission: true,
  },
  {
    code: 'shipping_agents.agents.create',
    screen: 'shipping_agents',
    subScreen: 'agents',
    action: 'create',
    nameAr: 'إضافة وكيل',
    nameEn: 'Create Agent',
    description: 'Add new agent',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.agents.edit',
    screen: 'shipping_agents',
    subScreen: 'agents',
    action: 'edit',
    nameAr: 'تعديل وكيل',
    nameEn: 'Edit Agent',
    description: 'Edit existing agent',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.agents.delete',
    screen: 'shipping_agents',
    subScreen: 'agents',
    action: 'delete',
    nameAr: 'حذف وكيل',
    nameEn: 'Delete Agent',
    description: 'Delete agent',
    category: 'shipping_agents',
    isViewPermission: false,
  },

  // Trips Registration
  {
    code: 'shipping_agents.trips.view',
    screen: 'shipping_agents',
    subScreen: 'trips',
    action: 'view',
    nameAr: 'عرض الرحلات',
    nameEn: 'View Trips',
    description: 'View trips registration tab',
    category: 'shipping_agents',
    isViewPermission: true,
  },
  {
    code: 'shipping_agents.trips.create',
    screen: 'shipping_agents',
    subScreen: 'trips',
    action: 'create',
    nameAr: 'تسجيل رحلة',
    nameEn: 'Register Trip',
    description: 'Register new trip',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.trips.edit',
    screen: 'shipping_agents',
    subScreen: 'trips',
    action: 'edit',
    nameAr: 'تعديل رحلة',
    nameEn: 'Edit Trip',
    description: 'Edit existing trip',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.trips.delete',
    screen: 'shipping_agents',
    subScreen: 'trips',
    action: 'delete',
    nameAr: 'حذف رحلة',
    nameEn: 'Delete Trip',
    description: 'Delete trip',
    category: 'shipping_agents',
    isViewPermission: false,
  },

  // Additional Fees
  {
    code: 'shipping_agents.fees.view',
    screen: 'shipping_agents',
    subScreen: 'fees',
    action: 'view',
    nameAr: 'عرض الرسوم الإضافية',
    nameEn: 'View Additional Fees',
    description: 'View additional fees tab',
    category: 'shipping_agents',
    isViewPermission: true,
  },
  {
    code: 'shipping_agents.fees.create',
    screen: 'shipping_agents',
    subScreen: 'fees',
    action: 'create',
    nameAr: 'إضافة رسم إضافي',
    nameEn: 'Create Additional Fee',
    description: 'Add new additional fee',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.fees.edit',
    screen: 'shipping_agents',
    subScreen: 'fees',
    action: 'edit',
    nameAr: 'تعديل رسم إضافي',
    nameEn: 'Edit Additional Fee',
    description: 'Edit existing additional fee',
    category: 'shipping_agents',
    isViewPermission: false,
  },
  {
    code: 'shipping_agents.fees.delete',
    screen: 'shipping_agents',
    subScreen: 'fees',
    action: 'delete',
    nameAr: 'حذف رسم إضافي',
    nameEn: 'Delete Additional Fee',
    description: 'Delete additional fee',
    category: 'shipping_agents',
    isViewPermission: false,
  },

  // ============================================
  // 4. Accounts Management (47 permissions)
  // ============================================
  // Treasury (2)
  {
    code: 'accounts.treasury.view',
    screen: 'accounts',
    subScreen: 'treasury',
    action: 'view',
    nameAr: 'عرض الخزينة',
    nameEn: 'View Treasury',
    description: 'View treasury tab',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.treasury.carry_forward',
    screen: 'accounts',
    subScreen: 'treasury',
    action: 'carry_forward',
    nameAr: 'ترحيل رصيد الخزينة',
    nameEn: 'Carry Forward Treasury Balance',
    description: 'Carry forward treasury balance',
    category: 'accounts',
    isViewPermission: false,
  },

  // Bank Accounts (5)
  {
    code: 'accounts.bank_accounts.view',
    screen: 'accounts',
    subScreen: 'bank_accounts',
    action: 'view',
    nameAr: 'عرض الحسابات البنكية',
    nameEn: 'View Bank Accounts',
    description: 'View bank accounts tab',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.bank_accounts.carry_forward_all',
    screen: 'accounts',
    subScreen: 'bank_accounts',
    action: 'carry_forward_all',
    nameAr: 'ترحيل جميع الأرصدة البنكية',
    nameEn: 'Carry Forward All Bank Balances',
    description: 'Carry forward all bank account balances',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.bank_accounts.create',
    screen: 'accounts',
    subScreen: 'bank_accounts',
    action: 'create',
    nameAr: 'إضافة حساب بنكي',
    nameEn: 'Create Bank Account',
    description: 'Add new bank account',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.bank_accounts.edit',
    screen: 'accounts',
    subScreen: 'bank_accounts',
    action: 'edit',
    nameAr: 'تعديل حساب بنكي',
    nameEn: 'Edit Bank Account',
    description: 'Edit existing bank account',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.bank_accounts.delete',
    screen: 'accounts',
    subScreen: 'bank_accounts',
    action: 'delete',
    nameAr: 'حذف حساب بنكي',
    nameEn: 'Delete Bank Account',
    description: 'Delete bank account',
    category: 'accounts',
    isViewPermission: false,
  },

  // Receipt Vouchers (6)
  {
    code: 'accounts.vouchers_receipt.view',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'view',
    nameAr: 'عرض سندات القبض',
    nameEn: 'View Receipt Vouchers',
    description: 'View receipt vouchers',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.vouchers_receipt.create',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'create',
    nameAr: 'إنشاء سند قبض',
    nameEn: 'Create Receipt Voucher',
    description: 'Create new receipt voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_receipt.preview',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'preview',
    nameAr: 'معاينة سند قبض',
    nameEn: 'Preview Receipt Voucher',
    description: 'Preview receipt voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_receipt.print',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'print',
    nameAr: 'طباعة سند قبض',
    nameEn: 'Print Receipt Voucher',
    description: 'Print receipt voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_receipt.edit',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'edit',
    nameAr: 'تعديل سند قبض',
    nameEn: 'Edit Receipt Voucher',
    description: 'Edit receipt voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_receipt.delete',
    screen: 'accounts',
    subScreen: 'vouchers_receipt',
    action: 'delete',
    nameAr: 'حذف سند قبض',
    nameEn: 'Delete Receipt Voucher',
    description: 'Delete receipt voucher',
    category: 'accounts',
    isViewPermission: false,
  },

  // Payment Vouchers (6)
  {
    code: 'accounts.vouchers_payment.view',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'view',
    nameAr: 'عرض سندات الصرف',
    nameEn: 'View Payment Vouchers',
    description: 'View payment vouchers',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.vouchers_payment.create',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'create',
    nameAr: 'إنشاء سند صرف',
    nameEn: 'Create Payment Voucher',
    description: 'Create new payment voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_payment.preview',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'preview',
    nameAr: 'معاينة سند صرف',
    nameEn: 'Preview Payment Voucher',
    description: 'Preview payment voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_payment.print',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'print',
    nameAr: 'طباعة سند صرف',
    nameEn: 'Print Payment Voucher',
    description: 'Print payment voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_payment.edit',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'edit',
    nameAr: 'تعديل سند صرف',
    nameEn: 'Edit Payment Voucher',
    description: 'Edit payment voucher',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.vouchers_payment.delete',
    screen: 'accounts',
    subScreen: 'vouchers_payment',
    action: 'delete',
    nameAr: 'حذف سند صرف',
    nameEn: 'Delete Payment Voucher',
    description: 'Delete payment voucher',
    category: 'accounts',
    isViewPermission: false,
  },

  // Customs Fees (4)
  {
    code: 'accounts.customs_fees.view',
    screen: 'accounts',
    subScreen: 'customs_fees',
    action: 'view',
    nameAr: 'عرض الرسوم الجمركية',
    nameEn: 'View Customs Fees',
    description: 'View customs fees tab',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.customs_fees.create_batch',
    screen: 'accounts',
    subScreen: 'customs_fees',
    action: 'create_batch',
    nameAr: 'إنشاء دفعة رسوم جمركية',
    nameEn: 'Create Customs Fee Batch',
    description: 'Create new customs fee batch',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.customs_fees.view_details',
    screen: 'accounts',
    subScreen: 'customs_fees',
    action: 'view_details',
    nameAr: 'عرض تفاصيل الدفعة',
    nameEn: 'View Batch Details',
    description: 'View customs fee batch details',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.customs_fees.delete',
    screen: 'accounts',
    subScreen: 'customs_fees',
    action: 'delete',
    nameAr: 'حذف دفعة رسوم جمركية',
    nameEn: 'Delete Customs Fee Batch',
    description: 'Delete customs fee batch',
    category: 'accounts',
    isViewPermission: false,
  },

  // Internal Transfers (5)
  {
    code: 'accounts.internal_transfers.view',
    screen: 'accounts',
    subScreen: 'internal_transfers',
    action: 'view',
    nameAr: 'عرض التحويلات الداخلية',
    nameEn: 'View Internal Transfers',
    description: 'View internal transfers tab',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.internal_transfers.create',
    screen: 'accounts',
    subScreen: 'internal_transfers',
    action: 'create',
    nameAr: 'إنشاء تحويل داخلي',
    nameEn: 'Create Internal Transfer',
    description: 'Create new internal transfer',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.internal_transfers.preview',
    screen: 'accounts',
    subScreen: 'internal_transfers',
    action: 'preview',
    nameAr: 'معاينة تحويل داخلي',
    nameEn: 'Preview Internal Transfer',
    description: 'Preview internal transfer',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.internal_transfers.edit',
    screen: 'accounts',
    subScreen: 'internal_transfers',
    action: 'edit',
    nameAr: 'تعديل تحويل داخلي',
    nameEn: 'Edit Internal Transfer',
    description: 'Edit internal transfer',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.internal_transfers.delete',
    screen: 'accounts',
    subScreen: 'internal_transfers',
    action: 'delete',
    nameAr: 'حذف تحويل داخلي',
    nameEn: 'Delete Internal Transfer',
    description: 'Delete internal transfer',
    category: 'accounts',
    isViewPermission: false,
  },

  // Voucher Search (1)
  {
    code: 'accounts.voucher_search.access',
    screen: 'accounts',
    subScreen: 'voucher_search',
    action: 'access',
    nameAr: 'الوصول إلى البحث عن السندات',
    nameEn: 'Access Voucher Search',
    description: 'Access voucher search tab',
    category: 'accounts',
    isViewPermission: true,
  },

  // Payroll (6)
  {
    code: 'accounts.payroll.view',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'view',
    nameAr: 'عرض الرواتب',
    nameEn: 'View Payroll',
    description: 'View payroll tab',
    category: 'accounts',
    isViewPermission: true,
  },
  {
    code: 'accounts.payroll.create',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'create',
    nameAr: 'إنشاء كشف رواتب',
    nameEn: 'Create Payroll',
    description: 'Create new payroll',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.payroll.preview',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'preview',
    nameAr: 'معاينة كشف رواتب',
    nameEn: 'Preview Payroll',
    description: 'Preview payroll',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.payroll.edit',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'edit',
    nameAr: 'تعديل كشف رواتب',
    nameEn: 'Edit Payroll',
    description: 'Edit payroll',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.payroll.approve',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'approve',
    nameAr: 'اعتماد كشف رواتب',
    nameEn: 'Approve Payroll',
    description: 'Approve payroll',
    category: 'accounts',
    isViewPermission: false,
  },
  {
    code: 'accounts.payroll.delete',
    screen: 'accounts',
    subScreen: 'payroll',
    action: 'delete',
    nameAr: 'حذف كشف رواتب',
    nameEn: 'Delete Payroll',
    description: 'Delete payroll',
    category: 'accounts',
    isViewPermission: false,
  },

  // ============================================
  // 5. Employees (4 permissions)
  // ============================================
  {
    code: 'employees.view',
    screen: 'employees',
    action: 'view',
    nameAr: 'عرض الموظفين',
    nameEn: 'View Employees',
    description: 'View employees screen',
    category: 'employees',
    isViewPermission: true,
  },
  {
    code: 'employees.create',
    screen: 'employees',
    action: 'create',
    nameAr: 'إضافة موظف',
    nameEn: 'Create Employee',
    description: 'Add new employee',
    category: 'employees',
    isViewPermission: false,
  },
  {
    code: 'employees.edit',
    screen: 'employees',
    action: 'edit',
    nameAr: 'تعديل موظف',
    nameEn: 'Edit Employee',
    description: 'Edit existing employee',
    category: 'employees',
    isViewPermission: false,
  },
  {
    code: 'employees.delete',
    screen: 'employees',
    action: 'delete',
    nameAr: 'حذف موظف',
    nameEn: 'Delete Employee',
    description: 'Delete employee',
    category: 'employees',
    isViewPermission: false,
  },

  // ============================================
  // 6. Reports (10 permissions)
  // ============================================
  // Financial Reports (6)
  {
    code: 'reports.financial.treasury_cash',
    screen: 'reports',
    subScreen: 'financial',
    action: 'treasury_cash',
    nameAr: 'تقرير الخزينة والنقدية',
    nameEn: 'Treasury and Cash Report',
    description: 'Access treasury and cash report',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.financial.bank_accounts',
    screen: 'reports',
    subScreen: 'financial',
    action: 'bank_accounts',
    nameAr: 'تقرير الحسابات البنكية',
    nameEn: 'Bank Accounts Report',
    description: 'Access bank accounts report',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.financial.income_expenses',
    screen: 'reports',
    subScreen: 'financial',
    action: 'income_expenses',
    nameAr: 'تقرير الإيرادات والمصروفات',
    nameEn: 'Income and Expenses Report',
    description: 'Access income and expenses report',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.financial.income_statement',
    screen: 'reports',
    subScreen: 'financial',
    action: 'income_statement',
    nameAr: 'قائمة الدخل',
    nameEn: 'Income Statement Report',
    description: 'Access income statement report',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.financial.general_journal',
    screen: 'reports',
    subScreen: 'financial',
    action: 'general_journal',
    nameAr: 'دفتر اليومية العامة',
    nameEn: 'General Journal Report',
    description: 'Access general journal report',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.financial.trial_balance',
    screen: 'reports',
    subScreen: 'financial',
    action: 'trial_balance',
    nameAr: 'ميزان المراجعة',
    nameEn: 'Trial Balance Report',
    description: 'Access trial balance report',
    category: 'reports',
    isViewPermission: true,
  },

  // Other Reports (4)
  {
    code: 'reports.customers.access',
    screen: 'reports',
    subScreen: 'customers',
    action: 'access',
    nameAr: 'تقارير العملاء',
    nameEn: 'Customer Reports',
    description: 'Access customer reports section',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.customs.access',
    screen: 'reports',
    subScreen: 'customs',
    action: 'access',
    nameAr: 'تقارير الجمارك',
    nameEn: 'Customs Reports',
    description: 'Access customs reports section',
    category: 'reports',
    isViewPermission: true,
  },
  {
    code: 'reports.shipping_agents.access',
    screen: 'reports',
    subScreen: 'shipping_agents',
    action: 'access',
    nameAr: 'تقارير الوكلاء الملاحيين',
    nameEn: 'Shipping Agents Reports',
    description: 'Access shipping agents reports section',
    category: 'reports',
    isViewPermission: true,
  },

  // ============================================
  // 7. Users Management (5 permissions)
  // ============================================
  {
    code: 'users.view',
    screen: 'users',
    action: 'view',
    nameAr: 'عرض المستخدمين',
    nameEn: 'View Users',
    description: 'View users management screen',
    category: 'users',
    isViewPermission: true,
  },
  {
    code: 'users.create',
    screen: 'users',
    action: 'create',
    nameAr: 'إضافة مستخدم',
    nameEn: 'Create User',
    description: 'Add new user',
    category: 'users',
    isViewPermission: false,
  },
  {
    code: 'users.edit',
    screen: 'users',
    action: 'edit',
    nameAr: 'تعديل مستخدم',
    nameEn: 'Edit User',
    description: 'Edit existing user',
    category: 'users',
    isViewPermission: false,
  },
  {
    code: 'users.delete',
    screen: 'users',
    action: 'delete',
    nameAr: 'حذف مستخدم',
    nameEn: 'Delete User',
    description: 'Delete user',
    category: 'users',
    isViewPermission: false,
  },
  {
    code: 'users.manage_permissions',
    screen: 'users',
    action: 'manage_permissions',
    nameAr: 'إدارة صلاحيات المستخدمين',
    nameEn: 'Manage User Permissions',
    description: 'Manage user permissions',
    category: 'users',
    isViewPermission: false,
  },
  // ============================================
  // 8. Settings (10 permissions)
  // ============================================
  {
    code: 'settings.expense_categories.view',
    screen: 'settings',
    subScreen: 'expense_categories',
    action: 'view',
    nameAr: 'إدارة تصنيفات المصروفات',
    nameEn: 'Manage Expense Categories',
    description: 'Access expense categories settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.invoice_templates.view',
    screen: 'settings',
    subScreen: 'invoice_templates',
    action: 'view',
    nameAr: 'إدارة بنود الفواتير',
    nameEn: 'Manage Invoice Templates',
    description: 'Access invoice templates settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.income_statement.config',
    screen: 'settings',
    subScreen: 'income_statement',
    action: 'config',
    nameAr: 'إعدادات قائمة الدخل',
    nameEn: 'Income Statement Config',
    description: 'Configure income statement',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.company.view',
    screen: 'settings',
    subScreen: 'company',
    action: 'view',
    nameAr: 'إعدادات الشركة',
    nameEn: 'Company Settings',
    description: 'Access company settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.backup.view',
    screen: 'settings',
    subScreen: 'backup',
    action: 'view',
    nameAr: 'النسخ الاحتياطي',
    nameEn: 'Backup Settings',
    description: 'Access backup settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.print.view',
    screen: 'settings',
    subScreen: 'print',
    action: 'view',
    nameAr: 'إعدادات الطباعة',
    nameEn: 'Print Settings',
    description: 'Access print settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.treasury_settings.view',
    screen: 'settings',
    subScreen: 'treasury',
    action: 'view',
    nameAr: 'إعدادات الخزنة',
    nameEn: 'Treasury Settings',
    description: 'Access treasury settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.carry_forward.view',
    screen: 'settings',
    subScreen: 'carry_forward',
    action: 'view',
    nameAr: 'إعدادات الترحيل',
    nameEn: 'Carry Forward Settings',
    description: 'Access carry forward settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.agent_settings.view',
    screen: 'settings',
    subScreen: 'agent_settings',
    action: 'view',
    nameAr: 'إعدادات الوكلاء',
    nameEn: 'Agent Settings',
    description: 'Access agent settings',
    category: 'settings',
    isViewPermission: true,
  },
  {
    code: 'settings.reset_system.access',
    screen: 'settings',
    subScreen: 'reset_system',
    action: 'access',
    nameAr: 'إعادة تعيين النظام',
    nameEn: 'Reset System',
    description: 'Access system reset',
    category: 'settings',
    isViewPermission: true,
  },
];

/**
 * Seed permissions into the database
 */
async function seedPermissions() {
  console.log('🌱 Starting permissions seed...');

  try {
    // Insert or update all permissions
    console.log(`📝 Upserting ${permissionsSeedData.length} permissions...`);

    for (const permission of permissionsSeedData) {
      await prisma.permission.upsert({
        where: { code: permission.code },
        update: {
          screen: permission.screen,
          subScreen: permission.subScreen,
          action: permission.action,
          nameAr: permission.nameAr,
          nameEn: permission.nameEn,
          description: permission.description,
          category: permission.category,
          isViewPermission: permission.isViewPermission,
        },
        create: permission,
      });
    }

    console.log('✅ Permissions seeded successfully!');
    console.log(`   Total permissions: ${permissionsSeedData.length}`);

    // Summary by screen
    const summary = permissionsSeedData.reduce((acc, perm) => {
      acc[perm.screen] = (acc[perm.screen] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    console.log('\n📊 Permissions by screen:');
    Object.entries(summary).forEach(([screen, count]) => {
      console.log(`   - ${screen}: ${count} permissions`);
    });

  } catch (error) {
    console.error('❌ Error seeding permissions:', error);
    throw error;
  }
}

/**
 * Main seed function
 */
async function main() {
  await seedPermissions();
}

// Execute seed
main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

export { permissionsSeedData };
